/*
 *  * Project: Ex2 India
 * Test: Dan Ryan TC
 * Generated by: Suraj Kumar (skumar@ex2india.com)
 * Generated on Sat Jun 12 11:26:09 GMT 2021.
 */

package org.Ex2FW;
import org.openqa.selenium.By;
import org.openqa.selenium.WebElement;
import org.testng.Assert;
import org.testng.annotations.Test;

import com.aventstack.extentreports.ExtentReports;
import com.aventstack.extentreports.ExtentTest;
import com.aventstack.extentreports.Status;
import com.aventstack.extentreports.reporter.ExtentSparkReporter;
import com.pageObjects.DanRyan;

public class DanRyanTest1 extends base {
	
	@Test
	public void Test1() throws Exception{
		
		ExtentSparkReporter spark = new ExtentSparkReporter("target/Spark.html");
		ExtentReports report = new ExtentReports();
		report.attachReporter(spark);
		ExtentTest mylog = report.createTest("DanRayn tc");
		
		String siteUrl = "https://www.danryanbuilders.com/";
		
		driver = initDriver();
		mylog.log(Status.INFO,"test case started");
		driver.get(siteUrl);
		mylog.log(Status.INFO,"Website opened");
		System.out.println("Website title is "+driver.getTitle());
		driver.manage().window().maximize();
		DanRyan dr = new DanRyan(driver);
		dr.verifyWebsiteLogo();
		mylog.log(Status.INFO,"Website logo verified success");
		dr.NavigateToCommPage();
		ScrollPagedown("700");
		//dr.OpenAndersonComm();
		  
		// 4. Does 'Dan Ryan Builders New Home Communitie...' contain 'Dan Ryan Builders New Home Communities'?
	    WebElement TitlePage1  = driver.findElement(By.xpath("//h1[. = 'Dan Ryan Builders New Home Communities']"));
	    Assert.assertTrue(TitlePage1.getText().contains("Dan Ryan Builders New Home Communities"));

	    // 5. Scroll window by ('0','400')
	    ScrollPagedown("400");

	    // 6. Does 'Our Communities' contain 'Our Communities'?
	    
	    WebElement OurCommLink  = driver.findElement(By.xpath("//h2[. = 'Our Communities']"));
	    Assert.assertTrue(OurCommLink.getText().contains("Our Communities"));

	    // 7. Click 'Anderson Grant'
	    
	    WebElement AndersonGt = driver.findElement(By.xpath("//h3/a[. = 'Anderson Grant']"));
	    AndersonGt.click();

	    // 8. Scroll window by ('0','500')
	    ScrollPagedown("500");

	    // 9. Does 'Anderson Grant1' contain 'Anderson Grant'?
	    
	    WebElement AndersonGtName = driver.findElement(By.xpath("//h1[. = 'Anderson Grant']"));
	    Assert.assertTrue(AndersonGtName.getText().contains("Anderson Grant"));

	    // 10. Does '3 - 4 Beds' contain '3 - 4 Beds'?
	    
	    WebElement Bedrange = driver.findElement(By.xpath("//li[. = '3 - 4 Beds']"));
	    Assert.assertTrue(Bedrange.getText().contains("3 - 4 Beds"));

	    // 11. Does '2 Car Garage' contain '2 Car Garage'?
	    
	    WebElement garagerange = driver.findElement(By.xpath("//li[. = '2 Car Garage']"));
	    Assert.assertTrue(garagerange.getText().contains("2 Car Garage"));

	    // 12. Does 'Request More Info' contain 'Request More Info'?
	    
	    WebElement requstinfo = driver.findElement(By.xpath("//h2[. = 'Request More Info']"));
	    Assert.assertTrue(requstinfo.getText().contains("Request More Info"));

	    // 13. Click 'Submit'
	    
	    WebElement requstinfoSubmit = driver.findElement(By.cssSelector("#RequestBrochureSumbitButton"));
	    requstinfoSubmit.click();

	    // 14. Does 'This field is required.1' contain 'This field is required.'?
	    
	    WebElement manfield = driver.findElement(By.xpath("//div[3]//label[. = 'This field is required.']"));
	    Assert.assertTrue(manfield.getText().contains("This field is required."));

	    // 15. Scroll window by ('0','500')
	    ScrollPagedown("500");

	    // 16. Does 'Sales Office' contain 'Sales Office'?
	    WebElement Salesoffice = driver.findElement(By.xpath("//h3[. = 'Sales Office']"));
	    Assert.assertTrue(Salesoffice.getText().contains("Sales Office"));

	    // 17. Does 'Hours' contain 'Hours'?
	    
	    WebElement SalesofficeHours = driver.findElement(By.xpath("//h3[. = 'Hours']"));
	    Assert.assertTrue(SalesofficeHours.getText().contains("Hours"));

	    // 18. Does 'Schools' contain 'Schools'?
	    
	    WebElement Schools = driver.findElement(By.xpath("//h3[. = 'Schools']"));
	    Assert.assertTrue(Schools.getText().contains("Schools"));

	    // 19. Does 'Dine & Shop' contain 'Dine & Shop'?
	    
	    WebElement DineShop = driver.findElement(By.xpath("//h3[. = 'Dine & Shop']"));
	    Assert.assertTrue(DineShop.getText().contains("Dine & Shop"));

	    // 20. Does 'Health & Fitness' contain 'Health & Fitness'?
	    
	    WebElement HealthFitness = driver.findElement(By.xpath("//h3[. = 'Health & Fitness']"));
	    Assert.assertTrue(HealthFitness.getText().contains("Health & Fitness"));

	    // 21. Scroll window by ('0','700')
	    ScrollPagedown("900");

	    
	    // 23. Does 'Plans Available' contain 'Plans Available'?
	    WebElement PlansAvail = driver.findElement(By.xpath("//h3[. = 'Plans Available']"));
	    Assert.assertTrue(PlansAvail.getText().contains("Plans Available"));

	    // 24. Click 'Parker'
	    WebElement parkerSpec = driver.findElement(By.xpath("//a[. = 'Parker']"));
	    parkerSpec.click();

	    // 25. Scroll window by ('0','700')
	    ScrollPagedown("700");

	    // 26. Does 'Parker1' contain 'Parker'?
	    
	    WebElement parkerSpecName = driver.findElement(By.xpath("//h1[. = 'Parker']"));
	    Assert.assertTrue(parkerSpecName.getText().contains("Parker"));

	    // 27. Scroll window by ('0','100')
	    ScrollPagedown("100");

	    // 28. Scroll window by ('0','500')
	    ScrollPagedown("500");

	    // 31. Scroll window by ('0','700')
	    ScrollPagedown("900");


	    // 35. Does 'Directions' contain 'Directions'?
	    
	    WebElement directions = driver.findElement(By.xpath("//h3[. = 'Directions']"));
	    Assert.assertTrue(directions.getText().contains("Directions"));
		
		
		mylog.log(Status.PASS, "test is passed.");
		report.flush();
		driver.quit();
	}	
}
